name: Install BATS
description: Install the Bash Automated Testing System (BATS)

runs:
  using: composite
  steps:
    - name: Install BATS
      shell: bash
      run: |
        git clone --depth 1 https://github.com/bats-core/bats-core.git /tmp/bats-core
        sudo /tmp/bats-core/install.sh /usr/local
        rm -rf /tmp/bats-core
