#![allow(clippy::needless_for_each)] // generated by utoipa derive macro

use utoipa::OpenApi;

use super::agent_handler;
use super::alert_handler;
use super::audit_handler;
use super::error;
use super::firewall_handler;
use super::health_handler;
use super::ips_handler;
use super::l7_handler;
use super::metrics_handler;
use super::ratelimit_handler;
use super::threatintel_handler;

#[allow(clippy::needless_for_each)] // generated by utoipa derive macro
#[derive(OpenApi)]
#[openapi(
    info(
        title = "eBPFsentinel Agent API",
        version = "1.0.0",
        description = "REST API for the eBPFsentinel network security agent.\n\n\
            Provides endpoints for managing firewall rules, IPS/IDS policies, \
            rate limiting, L7 filtering, threat intelligence, alerts, and audit logs.",
        license(name = "Apache-2.0"),
    ),
    paths(
        // Health
        health_handler::healthz,
        health_handler::readyz,
        // Agent
        agent_handler::agent_status,
        // Metrics
        metrics_handler::metrics,
        // Firewall
        firewall_handler::list_rules,
        firewall_handler::create_rule,
        firewall_handler::delete_rule,
        // L7
        l7_handler::list_l7_rules,
        l7_handler::create_l7_rule,
        l7_handler::delete_l7_rule,
        // IPS
        ips_handler::list_ips_rules,
        ips_handler::patch_ips_rule_mode,
        ips_handler::list_ips_blacklist,
        ips_handler::list_ips_domain_blocks,
        // Rate Limiting
        ratelimit_handler::list_ratelimit_rules,
        ratelimit_handler::create_ratelimit_rule,
        ratelimit_handler::delete_ratelimit_rule,
        // Alerts
        alert_handler::list_alerts,
        alert_handler::mark_false_positive,
        // Audit
        audit_handler::list_audit_logs,
        audit_handler::rule_history,
        // Threat Intelligence
        threatintel_handler::threatintel_status,
        threatintel_handler::list_iocs,
        threatintel_handler::list_feeds,
    ),
    components(schemas(
        // Error
        error::ErrorBody,
        error::ErrorDetail,
        // Health
        health_handler::HealthResponse,
        health_handler::ReadyResponse,
        // Agent
        agent_handler::AgentStatusResponse,
        // Firewall
        firewall_handler::CreateRuleRequest,
        firewall_handler::RuleResponse,
        // L7
        l7_handler::CreateL7RuleRequest,
        l7_handler::L7RuleResponse,
        // IPS
        ips_handler::IpsRuleResponse,
        ips_handler::BlacklistEntryResponse,
        ips_handler::PatchRuleModeRequest,
        ips_handler::DomainBlockResponse,
        // Rate Limiting
        ratelimit_handler::CreateRateLimitRuleRequest,
        ratelimit_handler::RateLimitRuleResponse,
        // Alerts
        alert_handler::AlertListResponse,
        alert_handler::AlertResponse,
        alert_handler::FalsePositiveResponse,
        // Audit
        audit_handler::AuditLogResponse,
        audit_handler::AuditEntryResponse,
        audit_handler::RuleHistoryResponse,
        audit_handler::RuleChangeResponse,
        // Threat Intelligence
        threatintel_handler::ThreatIntelStatusResponse,
        threatintel_handler::IocResponse,
        threatintel_handler::FeedResponse,
    )),
    tags(
        (name = "Health", description = "Liveness and readiness probes"),
        (name = "Agent", description = "Agent status and metadata"),
        (name = "Observability", description = "Prometheus metrics"),
        (name = "Firewall", description = "L3/L4 firewall rule management"),
        (name = "L7 Firewall", description = "Application-layer firewall rules"),
        (name = "IPS", description = "Intrusion prevention rules and blacklist"),
        (name = "Rate Limiting", description = "Rate limit policy management"),
        (name = "Alerts", description = "Alert queries and false-positive marking"),
        (name = "Audit", description = "Audit log queries and rule history"),
        (name = "Threat Intelligence", description = "Threat intel feeds and IOC status"),
    )
)]
pub struct ApiDoc;
