#![allow(clippy::needless_for_each)] // generated by utoipa derive macro

use utoipa::OpenApi;

use super::agent_handler;
use super::alert_handler;
use super::alias_handler;
use super::audit_handler;
use super::capture_handler;
use super::conntrack_handler;
use super::ddos_handler;
use super::dlp_handler;
use super::dns_handler;
use super::domain_handler;
use super::error;
use super::fingerprint_handler;
use super::firewall_handler;
use super::health_handler;
use super::ids_handler;
use super::ips_handler;
use super::l7_handler;
use super::lb_handler;
use super::metrics_handler;
use super::mitre_handler;
use super::nat_handler;
use super::ops_handler;
use super::ratelimit_handler;
use super::response_handler;
use super::routing_handler;
use super::threatintel_handler;
use super::zone_handler;

#[allow(clippy::needless_for_each)] // generated by utoipa derive macro
#[derive(OpenApi)]
#[openapi(
    info(
        title = "eBPFsentinel Agent API",
        version = "1.0.0",
        description = "REST API for the eBPFsentinel network security agent.\n\n\
            Provides endpoints for managing firewall rules, IPS/IDS policies, \
            rate limiting, L7 filtering, threat intelligence, alerts, and audit logs.",
        license(name = "Apache-2.0"),
    ),
    paths(
        // Health
        health_handler::healthz,
        health_handler::readyz,
        // Agent
        agent_handler::agent_status,
        // Metrics
        metrics_handler::metrics,
        // Firewall
        firewall_handler::list_rules,
        firewall_handler::create_rule,
        firewall_handler::delete_rule,
        // L7
        l7_handler::list_l7_rules,
        l7_handler::create_l7_rule,
        l7_handler::delete_l7_rule,
        // IPS
        ips_handler::list_ips_rules,
        ips_handler::patch_ips_rule_mode,
        ips_handler::list_ips_blacklist,
        ips_handler::list_ips_domain_blocks,
        // IDS
        ids_handler::ids_status,
        ids_handler::list_ids_rules,
        // Rate Limiting
        ratelimit_handler::list_ratelimit_rules,
        ratelimit_handler::create_ratelimit_rule,
        ratelimit_handler::delete_ratelimit_rule,
        // Alerts
        alert_handler::list_alerts,
        alert_handler::mark_false_positive,
        // Audit
        audit_handler::list_audit_logs,
        audit_handler::rule_history,
        // Threat Intelligence
        threatintel_handler::threatintel_status,
        threatintel_handler::list_iocs,
        threatintel_handler::list_feeds,
        // Ops
        ops_handler::reload_config,
        ops_handler::get_config,
        ops_handler::get_ebpf_status,
        // DNS
        dns_handler::list_dns_cache,
        dns_handler::dns_stats,
        dns_handler::list_dns_blocklist,
        dns_handler::flush_dns_cache,
        // Domains
        domain_handler::list_domain_reputations,
        domain_handler::add_to_blocklist,
        domain_handler::remove_from_blocklist,
        // DDoS
        ddos_handler::ddos_status,
        ddos_handler::ddos_attacks,
        ddos_handler::ddos_history,
        ddos_handler::list_ddos_policies,
        ddos_handler::create_ddos_policy,
        ddos_handler::delete_ddos_policy,
        // ConnTrack
        conntrack_handler::conntrack_status,
        conntrack_handler::list_connections,
        conntrack_handler::flush_connections,
        // DLP
        dlp_handler::dlp_status,
        dlp_handler::list_dlp_patterns,
        // NAT
        nat_handler::nat_status,
        nat_handler::list_nat_rules,
        nat_handler::list_nptv6_rules,
        nat_handler::create_nptv6_rule,
        nat_handler::delete_nptv6_rule,
        // Aliases
        alias_handler::alias_status,
        alias_handler::set_external_alias_content,
        // Routing
        routing_handler::routing_status,
        routing_handler::list_gateways,
        // Load Balancer
        lb_handler::lb_status,
        lb_handler::list_lb_services,
        lb_handler::get_lb_service,
        lb_handler::create_lb_service,
        lb_handler::delete_lb_service,
        // Zones
        zone_handler::zone_status,
        zone_handler::list_zones,
        zone_handler::list_zone_policies,
        // MITRE ATT&CK
        mitre_handler::mitre_coverage,
        // Fingerprints
        fingerprint_handler::fingerprint_summary,
        // Captures
        capture_handler::start_capture,
        capture_handler::list_captures,
        capture_handler::stop_capture,
        // Responses
        response_handler::create_response_action,
        response_handler::list_response_actions,
        response_handler::revoke_response_action,
    ),
    components(schemas(
        // Error
        error::ErrorBody,
        error::ErrorDetail,
        // Health
        health_handler::HealthResponse,
        health_handler::ReadyResponse,
        // Agent
        agent_handler::AgentStatusResponse,
        // Firewall
        firewall_handler::CreateRuleRequest,
        firewall_handler::RuleResponse,
        // L7
        l7_handler::CreateL7RuleRequest,
        l7_handler::L7RuleResponse,
        // IPS
        ips_handler::IpsRuleResponse,
        ips_handler::BlacklistEntryResponse,
        ips_handler::PatchRuleModeRequest,
        ips_handler::DomainBlockResponse,
        // IDS
        ids_handler::IdsStatusResponse,
        ids_handler::IdsRuleResponse,
        // Rate Limiting
        ratelimit_handler::CreateRateLimitRuleRequest,
        ratelimit_handler::RateLimitRuleResponse,
        // Alerts
        alert_handler::AlertListResponse,
        alert_handler::AlertResponse,
        alert_handler::FalsePositiveResponse,
        // Audit
        audit_handler::AuditLogResponse,
        audit_handler::AuditEntryResponse,
        audit_handler::RuleHistoryResponse,
        audit_handler::RuleChangeResponse,
        // Threat Intelligence
        threatintel_handler::ThreatIntelStatusResponse,
        threatintel_handler::IocResponse,
        threatintel_handler::FeedResponse,
        // Ops
        ops_handler::ReloadResponse,
        ops_handler::EbpfStatusResponse,
        ops_handler::ProgramStatus,
        // DNS
        dns_handler::DnsCacheEntryResponse,
        dns_handler::DnsCacheListResponse,
        dns_handler::DnsStatsResponse,
        dns_handler::TopQueriedEntry,
        dns_handler::BlocklistRuleResponse,
        dns_handler::DnsFlushResponse,
        // Domains
        domain_handler::DomainReputationResponse,
        domain_handler::DomainReputationListResponse,
        domain_handler::BlocklistAddRequest,
        domain_handler::BlocklistAddResponse,
        domain_handler::BlocklistRemoveResponse,
        // DDoS
        ddos_handler::DdosStatusResponse,
        ddos_handler::DdosAttackResponse,
        ddos_handler::DdosPolicyResponse,
        ddos_handler::CreateDdosPolicyRequest,
        // ConnTrack
        conntrack_handler::ConnTrackStatusResponse,
        conntrack_handler::ConnectionResponse,
        // DLP
        dlp_handler::DlpStatusResponse,
        dlp_handler::DlpPatternResponse,
        // NAT
        nat_handler::NatStatusResponse,
        nat_handler::NatRuleResponse,
        nat_handler::NptV6RuleResponse,
        nat_handler::CreateNptV6RuleRequest,
        // Aliases
        alias_handler::AliasStatusResponse,
        alias_handler::ExternalAliasContent,
        // Routing
        routing_handler::RoutingStatusResponse,
        routing_handler::GatewayResponse,
        // Load Balancer
        lb_handler::LbStatusResponse,
        lb_handler::LbServiceResponse,
        lb_handler::LbServiceDetailResponse,
        lb_handler::LbBackendResponse,
        lb_handler::CreateLbServiceRequest,
        lb_handler::CreateLbBackendRequest,
        // Zones
        zone_handler::ZoneStatusResponse,
        zone_handler::ZoneResponse,
        zone_handler::ZonePolicyResponse,
        // MITRE ATT&CK
        mitre_handler::MitreCoverageResponse,
        mitre_handler::TechniqueEntry,
        mitre_handler::TacticSummary,
        // Fingerprints
        fingerprint_handler::FingerprintSummaryResponse,
        // Captures
        capture_handler::StartCaptureRequest,
        capture_handler::CaptureResponse,
        capture_handler::CaptureListResponse,
        // Responses
        response_handler::CreateResponseRequest,
        response_handler::ResponseActionResponse,
        response_handler::ResponseListResponse,
    )),
    tags(
        (name = "Health", description = "Liveness and readiness probes"),
        (name = "Agent", description = "Agent status and metadata"),
        (name = "Observability", description = "Prometheus metrics"),
        (name = "Firewall", description = "L3/L4 firewall rule management"),
        (name = "L7 Firewall", description = "Application-layer firewall rules"),
        (name = "IPS", description = "Intrusion prevention rules and blacklist"),
        (name = "IDS", description = "Intrusion detection status and rules"),
        (name = "Rate Limiting", description = "Rate limit policy management"),
        (name = "Alerts", description = "Alert queries and false-positive marking"),
        (name = "Audit", description = "Audit log queries and rule history"),
        (name = "Threat Intelligence", description = "Threat intel feeds and IOC status"),
        (name = "Ops", description = "Operational endpoints: config reload, eBPF status"),
        (name = "DNS", description = "DNS cache, stats, and blocklist management"),
        (name = "Domains", description = "Domain reputation and blocklist management"),
        (name = "DDoS", description = "DDoS detection, mitigation, and policy management"),
        (name = "ConnTrack", description = "Connection tracking status and management"),
        (name = "DLP", description = "Data loss prevention status and patterns"),
        (name = "NAT", description = "Network address translation rules"),
        (name = "Aliases", description = "IP/port alias management"),
        (name = "Routing", description = "Policy routing and gateway management"),
        (name = "Load Balancer", description = "L4 load balancer service management"),
        (name = "Zones", description = "Security zone configuration and policies"),
        (name = "MITRE ATT&CK", description = "MITRE ATT&CK coverage and technique mapping"),
        (name = "Fingerprints", description = "JA4+ TLS fingerprint cache and analysis"),
        (name = "Captures", description = "Manual packet capture (pcap)"),
        (name = "Responses", description = "Manual time-bounded response actions (block/throttle with TTL)"),
    )
)]
pub struct ApiDoc;
